from typing import Protocol


class FreyaPort(Protocol):
    async def stop(self) -> None: ...
    async def fetch_auth_token(self) -> str: ...
    async def send_post_request(self, endpoint: str, payload: dict) -> str: ...
