from typing import Protocol


class FreyaPort(Protocol):
    async def stop(self) -> None: ...
    async def fetch_auth_token(self) -> str: ...
    async def send_post_request(self, endpoint: str, payload: dict) -> str: ...


class TroubleshootingPort(Protocol):
    async def stop(self) -> None: ...
    async def execute(self, im_id: str, ip_wan: str): ...
    async def ping_last_mile(self, im_id: str, service_code: str): ...


class NotificationPort(Protocol):
    async def stop(self) -> None: ...
    async def notify_via_telegram(self, template: dict) -> None: ...
