from typing import Protocol

from src.modules.freya.domain.entities import Transaction


class TransactionRepositoryPort(Protocol):
    async def get(self, transaction_id: int) -> Transaction | None: ...
    async def get_by_im_id(self, im_id: str) -> Transaction | None: ...
    async def create(self, transaction: Transaction) -> Transaction: ...
    async def update(self, transaction: Transaction) -> Transaction: ...
